project:
  type: website

website:
  title: "Iraitz's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/IraitzM
      - icon: linkedin
        href: https://linkedin.com/in/iraitzmontalban

format:
  html:
    theme: cosmo
    css: styles.css



