project:
  type: website

execute:
  freeze: auto

website:
  title: "Iraitz's blog"
  google-analytics: "G-MXHDHE1HP5"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/IraitzM
      - icon: linkedin
        href: https://linkedin.com/in/iraitzmontalban

format:
  html:
    include-in-header: static/code_head.html
    theme: cosmo
    css: styles.css

# Some SEO
metadata:
  lang: en
  author: "Iraitz Montalbán"
  twitter-card: false
  open-graph: true

resources:
  - robots.txt


